[package]
name = "trypema"
version = "0.1.0-dev.1"
edition = "2024"
readme = "README.md"
description = "High-performance rate limiting primitives in Rust, designed for concurrency safety, low overhead, and predictable latency."
license = "MIT"
repository = "https://github.com/dev-davexoyinbo/trypema"
categories = ["algorithms", "concurrency", "data-structures"]
keywords = [
  "rate-limiting",
  "rate-limiter",
  "throttling",
  "concurrency",
  "atomic",
]

[dependencies]
dashmap = "6.1.0"
tracing = "0.1.44"
